language: elixir
elixir:
  - 1.10.0
  - 1.11.0
  - 1.12.0
otp_release:
  - 22.1
  - 23.0
  - 24.0
matrix:
  exclude:
    - elixir: 1.10.0
      otp_release: 23.0
    - elixir: 1.10.0
      otp_release: 24.0
    - elixir: 1.11.0
      otp_release: 24.0
services:
  - rabbitmq
addons:
  apt:
    packages:
      - rabbitmq-server
